//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeriaVirtual.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATOS
    {
        public CONTRATOS()
        {
            this.POSTULACION = new HashSet<POSTULACION>();
        }
    
        public decimal CONTRATOID { get; set; }
        public System.DateTime FECHAINICIO { get; set; }
        public System.DateTime FECHAFINALIZACION { get; set; }
        public string TIPOCONTRATO { get; set; }
        public decimal ESTADOCONTRATOID { get; set; }
        public string DEMANDA { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public decimal USUARIOID { get; set; }
        public Nullable<short> PUBLISHED { get; set; }
    
        public virtual ESTADOCONTRATO ESTADOCONTRATO { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
        public virtual ICollection<POSTULACION> POSTULACION { get; set; }
    }
}
