//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeriaVirtual.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADOVENTA
    {
        public ESTADOVENTA()
        {
            this.VENTAS = new HashSet<VENTAS>();
        }
    
        public decimal ESTADOVENTAID { get; set; }
        public string NOMBREESTADOVENTA { get; set; }
    
        public virtual ICollection<VENTAS> VENTAS { get; set; }
    }
}
