//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeriaVirtual.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADOCONTRATO
    {
        public ESTADOCONTRATO()
        {
            this.CONTRATOS = new HashSet<CONTRATOS>();
        }
    
        public decimal ESTADOCONTRATOID { get; set; }
        public string NOMBREESTADO { get; set; }
    
        public virtual ICollection<CONTRATOS> CONTRATOS { get; set; }
    }
}
