//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeriaVirtual.DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class FeriaVirtualEntities : DbContext
    {
        public FeriaVirtualEntities()
            : base("name=FeriaVirtualEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<CONTRATOS> CONTRATOS { get; set; }
        public DbSet<ESTADOCONTRATO> ESTADOCONTRATO { get; set; }
        public DbSet<ESTADOVENTA> ESTADOVENTA { get; set; }
        public DbSet<MEDIOTRANSPORTE> MEDIOTRANSPORTE { get; set; }
        public DbSet<PAGO> PAGO { get; set; }
        public DbSet<POSTULACION> POSTULACION { get; set; }
        public DbSet<PRODUCTOR> PRODUCTOR { get; set; }
        public DbSet<PRODUCTOS> PRODUCTOS { get; set; }
        public DbSet<SUBASTA> SUBASTA { get; set; }
        public DbSet<SUBASTA_MEDIO> SUBASTA_MEDIO { get; set; }
        public DbSet<TIPOSUSUARIO> TIPOSUSUARIO { get; set; }
        public DbSet<TRANSPORTE> TRANSPORTE { get; set; }
        public DbSet<TRANSPORTISTA> TRANSPORTISTA { get; set; }
        public DbSet<USUARIOS> USUARIOS { get; set; }
        public DbSet<VENTA_PRODUCTO> VENTA_PRODUCTO { get; set; }
        public DbSet<VENTAS> VENTAS { get; set; }
    
        public virtual int DELETE_CONTRATO(Nullable<decimal> p_CONTRATOID)
        {
            var p_CONTRATOIDParameter = p_CONTRATOID.HasValue ?
                new ObjectParameter("P_CONTRATOID", p_CONTRATOID) :
                new ObjectParameter("P_CONTRATOID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_CONTRATO", p_CONTRATOIDParameter);
        }
    
        public virtual int DELETE_MEDIOTRANSPORTE(Nullable<decimal> p_MEDIOID)
        {
            var p_MEDIOIDParameter = p_MEDIOID.HasValue ?
                new ObjectParameter("P_MEDIOID", p_MEDIOID) :
                new ObjectParameter("P_MEDIOID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_MEDIOTRANSPORTE", p_MEDIOIDParameter);
        }
    
        public virtual int DELETE_PAGO(Nullable<decimal> p_PAGOID)
        {
            var p_PAGOIDParameter = p_PAGOID.HasValue ?
                new ObjectParameter("P_PAGOID", p_PAGOID) :
                new ObjectParameter("P_PAGOID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_PAGO", p_PAGOIDParameter);
        }
    
        public virtual int DELETE_POSTULACION(Nullable<decimal> p_POSTULACIONID)
        {
            var p_POSTULACIONIDParameter = p_POSTULACIONID.HasValue ?
                new ObjectParameter("P_POSTULACIONID", p_POSTULACIONID) :
                new ObjectParameter("P_POSTULACIONID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_POSTULACION", p_POSTULACIONIDParameter);
        }
    
        public virtual int DELETE_PRODUCTOS(Nullable<decimal> p_PRODUCTOID)
        {
            var p_PRODUCTOIDParameter = p_PRODUCTOID.HasValue ?
                new ObjectParameter("P_PRODUCTOID", p_PRODUCTOID) :
                new ObjectParameter("P_PRODUCTOID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_PRODUCTOS", p_PRODUCTOIDParameter);
        }
    
        public virtual int DELETE_SUBASTA(Nullable<decimal> p_SUBASTAID)
        {
            var p_SUBASTAIDParameter = p_SUBASTAID.HasValue ?
                new ObjectParameter("P_SUBASTAID", p_SUBASTAID) :
                new ObjectParameter("P_SUBASTAID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_SUBASTA", p_SUBASTAIDParameter);
        }
    
        public virtual int DELETE_SUBASTA_MEDIO(Nullable<decimal> p_MEDIOID, Nullable<decimal> p_SUBASTAID)
        {
            var p_MEDIOIDParameter = p_MEDIOID.HasValue ?
                new ObjectParameter("P_MEDIOID", p_MEDIOID) :
                new ObjectParameter("P_MEDIOID", typeof(decimal));
    
            var p_SUBASTAIDParameter = p_SUBASTAID.HasValue ?
                new ObjectParameter("P_SUBASTAID", p_SUBASTAID) :
                new ObjectParameter("P_SUBASTAID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_SUBASTA_MEDIO", p_MEDIOIDParameter, p_SUBASTAIDParameter);
        }
    
        public virtual int DELETE_TRANSPORTE(Nullable<decimal> p_TRANSPORTEID)
        {
            var p_TRANSPORTEIDParameter = p_TRANSPORTEID.HasValue ?
                new ObjectParameter("P_TRANSPORTEID", p_TRANSPORTEID) :
                new ObjectParameter("P_TRANSPORTEID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_TRANSPORTE", p_TRANSPORTEIDParameter);
        }
    
        public virtual int DELETE_USUARIOS(Nullable<decimal> p_USUARIOID)
        {
            var p_USUARIOIDParameter = p_USUARIOID.HasValue ?
                new ObjectParameter("P_USUARIOID", p_USUARIOID) :
                new ObjectParameter("P_USUARIOID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_USUARIOS", p_USUARIOIDParameter);
        }
    
        public virtual int DELETE_VENTA_PRODUCTO(Nullable<decimal> p_VENTAID, Nullable<decimal> p_PRODUCTOID)
        {
            var p_VENTAIDParameter = p_VENTAID.HasValue ?
                new ObjectParameter("P_VENTAID", p_VENTAID) :
                new ObjectParameter("P_VENTAID", typeof(decimal));
    
            var p_PRODUCTOIDParameter = p_PRODUCTOID.HasValue ?
                new ObjectParameter("P_PRODUCTOID", p_PRODUCTOID) :
                new ObjectParameter("P_PRODUCTOID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_VENTA_PRODUCTO", p_VENTAIDParameter, p_PRODUCTOIDParameter);
        }
    
        public virtual int DELETE_VENTAS(Nullable<decimal> p_VENTAID)
        {
            var p_VENTAIDParameter = p_VENTAID.HasValue ?
                new ObjectParameter("P_VENTAID", p_VENTAID) :
                new ObjectParameter("P_VENTAID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETE_VENTAS", p_VENTAIDParameter);
        }
    
        public virtual int FINISH_SUBASTA(Nullable<decimal> p_SUBASTAID, Nullable<decimal> p_FINISHED)
        {
            var p_SUBASTAIDParameter = p_SUBASTAID.HasValue ?
                new ObjectParameter("P_SUBASTAID", p_SUBASTAID) :
                new ObjectParameter("P_SUBASTAID", typeof(decimal));
    
            var p_FINISHEDParameter = p_FINISHED.HasValue ?
                new ObjectParameter("P_FINISHED", p_FINISHED) :
                new ObjectParameter("P_FINISHED", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FINISH_SUBASTA", p_SUBASTAIDParameter, p_FINISHEDParameter);
        }
    
        public virtual int GET_ALL_CLIENTES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_ALL_CLIENTES");
        }
    
        public virtual int GET_ALL_CONTRATOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_ALL_CONTRATOS");
        }
    
        public virtual int GET_ALL_MEDIOTRANSPORTE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_ALL_MEDIOTRANSPORTE");
        }
    
        public virtual int GET_ALL_PAGOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_ALL_PAGOS");
        }
    
        public virtual int GET_ALL_POSTULACIONES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_ALL_POSTULACIONES");
        }
    
        public virtual int GET_ALL_PRODUCTORES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_ALL_PRODUCTORES");
        }
    
        public virtual int GET_ALL_PRODUCTOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_ALL_PRODUCTOS");
        }
    
        public virtual int GET_ALL_SUBASTA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_ALL_SUBASTA");
        }
    
        public virtual int GET_ALL_SUBASTA_MEDIO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_ALL_SUBASTA_MEDIO");
        }
    
        public virtual int GET_ALL_SUBMEDIO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_ALL_SUBMEDIO");
        }
    
        public virtual int GET_ALL_TRANSPORTE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_ALL_TRANSPORTE");
        }
    
        public virtual int GET_ALL_TRANSPORTISTA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_ALL_TRANSPORTISTA");
        }
    
        public virtual int GET_ALL_USUARIOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_ALL_USUARIOS");
        }
    
        public virtual int GET_ALL_VENTA_PRODUCTO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_ALL_VENTA_PRODUCTO");
        }
    
        public virtual int GET_ALL_VENTAS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_ALL_VENTAS");
        }
    
        public virtual int GET_CLIENTE_BY_ID(Nullable<decimal> p_CLIENTEID)
        {
            var p_CLIENTEIDParameter = p_CLIENTEID.HasValue ?
                new ObjectParameter("P_CLIENTEID", p_CLIENTEID) :
                new ObjectParameter("P_CLIENTEID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_CLIENTE_BY_ID", p_CLIENTEIDParameter);
        }
    
        public virtual int GET_CONTRATO_BY_ID(Nullable<decimal> p_CONTRATO_ID)
        {
            var p_CONTRATO_IDParameter = p_CONTRATO_ID.HasValue ?
                new ObjectParameter("P_CONTRATO_ID", p_CONTRATO_ID) :
                new ObjectParameter("P_CONTRATO_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_CONTRATO_BY_ID", p_CONTRATO_IDParameter);
        }
    
        public virtual int GET_MEDIOTRANSPORTE_BY_ID(Nullable<decimal> p_MEDIOID)
        {
            var p_MEDIOIDParameter = p_MEDIOID.HasValue ?
                new ObjectParameter("P_MEDIOID", p_MEDIOID) :
                new ObjectParameter("P_MEDIOID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_MEDIOTRANSPORTE_BY_ID", p_MEDIOIDParameter);
        }
    
        public virtual int GET_PAGO_BY_ID(Nullable<decimal> p_PAGOID)
        {
            var p_PAGOIDParameter = p_PAGOID.HasValue ?
                new ObjectParameter("P_PAGOID", p_PAGOID) :
                new ObjectParameter("P_PAGOID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_PAGO_BY_ID", p_PAGOIDParameter);
        }
    
        public virtual int GET_POSTULACION_BY_CONTRACT(Nullable<decimal> p_CONTRATOID)
        {
            var p_CONTRATOIDParameter = p_CONTRATOID.HasValue ?
                new ObjectParameter("P_CONTRATOID", p_CONTRATOID) :
                new ObjectParameter("P_CONTRATOID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_POSTULACION_BY_CONTRACT", p_CONTRATOIDParameter);
        }
    
        public virtual int GET_POSTULACION_BY_ID(Nullable<decimal> p_POSTULACIONID)
        {
            var p_POSTULACIONIDParameter = p_POSTULACIONID.HasValue ?
                new ObjectParameter("P_POSTULACIONID", p_POSTULACIONID) :
                new ObjectParameter("P_POSTULACIONID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_POSTULACION_BY_ID", p_POSTULACIONIDParameter);
        }
    
        public virtual int GET_POSTULACION_BY_PRODUCTOR(Nullable<decimal> p_PRODUCTORID)
        {
            var p_PRODUCTORIDParameter = p_PRODUCTORID.HasValue ?
                new ObjectParameter("P_PRODUCTORID", p_PRODUCTORID) :
                new ObjectParameter("P_PRODUCTORID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_POSTULACION_BY_PRODUCTOR", p_PRODUCTORIDParameter);
        }
    
        public virtual int GET_PRODUCTO_BY_ID(Nullable<decimal> p_PRODUCTOID)
        {
            var p_PRODUCTOIDParameter = p_PRODUCTOID.HasValue ?
                new ObjectParameter("P_PRODUCTOID", p_PRODUCTOID) :
                new ObjectParameter("P_PRODUCTOID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_PRODUCTO_BY_ID", p_PRODUCTOIDParameter);
        }
    
        public virtual int GET_PRODUCTOR_BY_ID(Nullable<decimal> p_PRODUCTORID)
        {
            var p_PRODUCTORIDParameter = p_PRODUCTORID.HasValue ?
                new ObjectParameter("P_PRODUCTORID", p_PRODUCTORID) :
                new ObjectParameter("P_PRODUCTORID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_PRODUCTOR_BY_ID", p_PRODUCTORIDParameter);
        }
    
        public virtual int GET_PRODUCTOS_BY_PRODUCTOR(Nullable<decimal> p_PRODUCTORID)
        {
            var p_PRODUCTORIDParameter = p_PRODUCTORID.HasValue ?
                new ObjectParameter("P_PRODUCTORID", p_PRODUCTORID) :
                new ObjectParameter("P_PRODUCTORID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_PRODUCTOS_BY_PRODUCTOR", p_PRODUCTORIDParameter);
        }
    
        public virtual int GET_PUBLISHED_CONTRATOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_PUBLISHED_CONTRATOS");
        }
    
        public virtual int GET_SELECTED_POSTULACION(Nullable<decimal> p_CONTRATOID)
        {
            var p_CONTRATOIDParameter = p_CONTRATOID.HasValue ?
                new ObjectParameter("P_CONTRATOID", p_CONTRATOID) :
                new ObjectParameter("P_CONTRATOID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_SELECTED_POSTULACION", p_CONTRATOIDParameter);
        }
    
        public virtual int GET_SUBASTA_BY_ID(Nullable<decimal> p_SUBASTAID)
        {
            var p_SUBASTAIDParameter = p_SUBASTAID.HasValue ?
                new ObjectParameter("P_SUBASTAID", p_SUBASTAID) :
                new ObjectParameter("P_SUBASTAID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_SUBASTA_BY_ID", p_SUBASTAIDParameter);
        }
    
        public virtual int GET_SUBASTA_MEDIO_BY_ID(Nullable<decimal> p_MEDIOID, Nullable<decimal> p_SUBASTAID)
        {
            var p_MEDIOIDParameter = p_MEDIOID.HasValue ?
                new ObjectParameter("P_MEDIOID", p_MEDIOID) :
                new ObjectParameter("P_MEDIOID", typeof(decimal));
    
            var p_SUBASTAIDParameter = p_SUBASTAID.HasValue ?
                new ObjectParameter("P_SUBASTAID", p_SUBASTAID) :
                new ObjectParameter("P_SUBASTAID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_SUBASTA_MEDIO_BY_ID", p_MEDIOIDParameter, p_SUBASTAIDParameter);
        }
    
        public virtual int GET_TRANSPORTE_BY_ID(Nullable<decimal> p_TRANSPORTEID)
        {
            var p_TRANSPORTEIDParameter = p_TRANSPORTEID.HasValue ?
                new ObjectParameter("P_TRANSPORTEID", p_TRANSPORTEID) :
                new ObjectParameter("P_TRANSPORTEID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_TRANSPORTE_BY_ID", p_TRANSPORTEIDParameter);
        }
    
        public virtual int GET_TRANSPORTISTA_BY_ID(Nullable<decimal> p_TRANSPORTISTAID)
        {
            var p_TRANSPORTISTAIDParameter = p_TRANSPORTISTAID.HasValue ?
                new ObjectParameter("P_TRANSPORTISTAID", p_TRANSPORTISTAID) :
                new ObjectParameter("P_TRANSPORTISTAID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_TRANSPORTISTA_BY_ID", p_TRANSPORTISTAIDParameter);
        }
    
        public virtual int GET_UNFINISHED_SUBASTA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_UNFINISHED_SUBASTA");
        }
    
        public virtual int GET_USUARIO_BY_ID(Nullable<decimal> p_USUARIOID)
        {
            var p_USUARIOIDParameter = p_USUARIOID.HasValue ?
                new ObjectParameter("P_USUARIOID", p_USUARIOID) :
                new ObjectParameter("P_USUARIOID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_USUARIO_BY_ID", p_USUARIOIDParameter);
        }
    
        public virtual int GET_VENTA_BY_ID(Nullable<decimal> p_VENTAID)
        {
            var p_VENTAIDParameter = p_VENTAID.HasValue ?
                new ObjectParameter("P_VENTAID", p_VENTAID) :
                new ObjectParameter("P_VENTAID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_VENTA_BY_ID", p_VENTAIDParameter);
        }
    
        public virtual int GET_VENTA_BY_TYPE(string p_TIPOVENTA)
        {
            var p_TIPOVENTAParameter = p_TIPOVENTA != null ?
                new ObjectParameter("P_TIPOVENTA", p_TIPOVENTA) :
                new ObjectParameter("P_TIPOVENTA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_VENTA_BY_TYPE", p_TIPOVENTAParameter);
        }
    
        public virtual int GET_VENTA_PRODUCTO_BY_ID(Nullable<decimal> p_VENTAID, Nullable<decimal> p_PRODUCTOID)
        {
            var p_VENTAIDParameter = p_VENTAID.HasValue ?
                new ObjectParameter("P_VENTAID", p_VENTAID) :
                new ObjectParameter("P_VENTAID", typeof(decimal));
    
            var p_PRODUCTOIDParameter = p_PRODUCTOID.HasValue ?
                new ObjectParameter("P_PRODUCTOID", p_PRODUCTOID) :
                new ObjectParameter("P_PRODUCTOID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GET_VENTA_PRODUCTO_BY_ID", p_VENTAIDParameter, p_PRODUCTOIDParameter);
        }
    
        public virtual int INSERT_CONTRATO(Nullable<System.DateTime> p_FECHAINICIO, Nullable<System.DateTime> p_FECHAFINALIZACION, string p_TIPOCONTRATO, Nullable<decimal> p_ESTADOCONTRATOID, string p_DEMANDA, Nullable<decimal> p_CANTIDAD, Nullable<decimal> p_USUARIOID)
        {
            var p_FECHAINICIOParameter = p_FECHAINICIO.HasValue ?
                new ObjectParameter("P_FECHAINICIO", p_FECHAINICIO) :
                new ObjectParameter("P_FECHAINICIO", typeof(System.DateTime));
    
            var p_FECHAFINALIZACIONParameter = p_FECHAFINALIZACION.HasValue ?
                new ObjectParameter("P_FECHAFINALIZACION", p_FECHAFINALIZACION) :
                new ObjectParameter("P_FECHAFINALIZACION", typeof(System.DateTime));
    
            var p_TIPOCONTRATOParameter = p_TIPOCONTRATO != null ?
                new ObjectParameter("P_TIPOCONTRATO", p_TIPOCONTRATO) :
                new ObjectParameter("P_TIPOCONTRATO", typeof(string));
    
            var p_ESTADOCONTRATOIDParameter = p_ESTADOCONTRATOID.HasValue ?
                new ObjectParameter("P_ESTADOCONTRATOID", p_ESTADOCONTRATOID) :
                new ObjectParameter("P_ESTADOCONTRATOID", typeof(decimal));
    
            var p_DEMANDAParameter = p_DEMANDA != null ?
                new ObjectParameter("P_DEMANDA", p_DEMANDA) :
                new ObjectParameter("P_DEMANDA", typeof(string));
    
            var p_CANTIDADParameter = p_CANTIDAD.HasValue ?
                new ObjectParameter("P_CANTIDAD", p_CANTIDAD) :
                new ObjectParameter("P_CANTIDAD", typeof(decimal));
    
            var p_USUARIOIDParameter = p_USUARIOID.HasValue ?
                new ObjectParameter("P_USUARIOID", p_USUARIOID) :
                new ObjectParameter("P_USUARIOID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_CONTRATO", p_FECHAINICIOParameter, p_FECHAFINALIZACIONParameter, p_TIPOCONTRATOParameter, p_ESTADOCONTRATOIDParameter, p_DEMANDAParameter, p_CANTIDADParameter, p_USUARIOIDParameter);
        }
    
        public virtual int INSERT_MEDIOTRANSPORTE(string p_PATENTE, Nullable<decimal> p_ANCHO, Nullable<decimal> p_LARGO, Nullable<decimal> p_ALTO, Nullable<decimal> p_PRECIO, Nullable<decimal> p_CAPACIDAD, Nullable<decimal> p_REFRIGERADO, Nullable<decimal> p_TRANSPORTISTAID)
        {
            var p_PATENTEParameter = p_PATENTE != null ?
                new ObjectParameter("P_PATENTE", p_PATENTE) :
                new ObjectParameter("P_PATENTE", typeof(string));
    
            var p_ANCHOParameter = p_ANCHO.HasValue ?
                new ObjectParameter("P_ANCHO", p_ANCHO) :
                new ObjectParameter("P_ANCHO", typeof(decimal));
    
            var p_LARGOParameter = p_LARGO.HasValue ?
                new ObjectParameter("P_LARGO", p_LARGO) :
                new ObjectParameter("P_LARGO", typeof(decimal));
    
            var p_ALTOParameter = p_ALTO.HasValue ?
                new ObjectParameter("P_ALTO", p_ALTO) :
                new ObjectParameter("P_ALTO", typeof(decimal));
    
            var p_PRECIOParameter = p_PRECIO.HasValue ?
                new ObjectParameter("P_PRECIO", p_PRECIO) :
                new ObjectParameter("P_PRECIO", typeof(decimal));
    
            var p_CAPACIDADParameter = p_CAPACIDAD.HasValue ?
                new ObjectParameter("P_CAPACIDAD", p_CAPACIDAD) :
                new ObjectParameter("P_CAPACIDAD", typeof(decimal));
    
            var p_REFRIGERADOParameter = p_REFRIGERADO.HasValue ?
                new ObjectParameter("P_REFRIGERADO", p_REFRIGERADO) :
                new ObjectParameter("P_REFRIGERADO", typeof(decimal));
    
            var p_TRANSPORTISTAIDParameter = p_TRANSPORTISTAID.HasValue ?
                new ObjectParameter("P_TRANSPORTISTAID", p_TRANSPORTISTAID) :
                new ObjectParameter("P_TRANSPORTISTAID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_MEDIOTRANSPORTE", p_PATENTEParameter, p_ANCHOParameter, p_LARGOParameter, p_ALTOParameter, p_PRECIOParameter, p_CAPACIDADParameter, p_REFRIGERADOParameter, p_TRANSPORTISTAIDParameter);
        }
    
        public virtual int INSERT_PAGO(Nullable<System.DateTime> p_FECHA_PAGO, Nullable<decimal> p_PAGO, Nullable<decimal> p_VENTAID, Nullable<decimal> p_USUARIOID)
        {
            var p_FECHA_PAGOParameter = p_FECHA_PAGO.HasValue ?
                new ObjectParameter("P_FECHA_PAGO", p_FECHA_PAGO) :
                new ObjectParameter("P_FECHA_PAGO", typeof(System.DateTime));
    
            var p_PAGOParameter = p_PAGO.HasValue ?
                new ObjectParameter("P_PAGO", p_PAGO) :
                new ObjectParameter("P_PAGO", typeof(decimal));
    
            var p_VENTAIDParameter = p_VENTAID.HasValue ?
                new ObjectParameter("P_VENTAID", p_VENTAID) :
                new ObjectParameter("P_VENTAID", typeof(decimal));
    
            var p_USUARIOIDParameter = p_USUARIOID.HasValue ?
                new ObjectParameter("P_USUARIOID", p_USUARIOID) :
                new ObjectParameter("P_USUARIOID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_PAGO", p_FECHA_PAGOParameter, p_PAGOParameter, p_VENTAIDParameter, p_USUARIOIDParameter);
        }
    
        public virtual int INSERT_POSTULACION(Nullable<decimal> p_PRECIO, Nullable<decimal> p_CANTIDAD, Nullable<System.DateTime> p_FECHACOSECHA, Nullable<decimal> p_CONTRATOID, Nullable<decimal> p_PRODUCTORID)
        {
            var p_PRECIOParameter = p_PRECIO.HasValue ?
                new ObjectParameter("P_PRECIO", p_PRECIO) :
                new ObjectParameter("P_PRECIO", typeof(decimal));
    
            var p_CANTIDADParameter = p_CANTIDAD.HasValue ?
                new ObjectParameter("P_CANTIDAD", p_CANTIDAD) :
                new ObjectParameter("P_CANTIDAD", typeof(decimal));
    
            var p_FECHACOSECHAParameter = p_FECHACOSECHA.HasValue ?
                new ObjectParameter("P_FECHACOSECHA", p_FECHACOSECHA) :
                new ObjectParameter("P_FECHACOSECHA", typeof(System.DateTime));
    
            var p_CONTRATOIDParameter = p_CONTRATOID.HasValue ?
                new ObjectParameter("P_CONTRATOID", p_CONTRATOID) :
                new ObjectParameter("P_CONTRATOID", typeof(decimal));
    
            var p_PRODUCTORIDParameter = p_PRODUCTORID.HasValue ?
                new ObjectParameter("P_PRODUCTORID", p_PRODUCTORID) :
                new ObjectParameter("P_PRODUCTORID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_POSTULACION", p_PRECIOParameter, p_CANTIDADParameter, p_FECHACOSECHAParameter, p_CONTRATOIDParameter, p_PRODUCTORIDParameter);
        }
    
        public virtual int INSERT_PRODUCTO(string p_NOMBRE, Nullable<decimal> p_PRECIO, Nullable<decimal> p_STOCK, Nullable<decimal> p_PRODUCTORID)
        {
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("P_NOMBRE", p_NOMBRE) :
                new ObjectParameter("P_NOMBRE", typeof(string));
    
            var p_PRECIOParameter = p_PRECIO.HasValue ?
                new ObjectParameter("P_PRECIO", p_PRECIO) :
                new ObjectParameter("P_PRECIO", typeof(decimal));
    
            var p_STOCKParameter = p_STOCK.HasValue ?
                new ObjectParameter("P_STOCK", p_STOCK) :
                new ObjectParameter("P_STOCK", typeof(decimal));
    
            var p_PRODUCTORIDParameter = p_PRODUCTORID.HasValue ?
                new ObjectParameter("P_PRODUCTORID", p_PRODUCTORID) :
                new ObjectParameter("P_PRODUCTORID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_PRODUCTO", p_NOMBREParameter, p_PRECIOParameter, p_STOCKParameter, p_PRODUCTORIDParameter);
        }
    
        public virtual int INSERT_SUBASTA(Nullable<decimal> p_VENTAID, Nullable<System.DateTime> p_FECHAINICIO, Nullable<System.DateTime> p_FECHATERMINO, Nullable<decimal> p_ANCHO, Nullable<decimal> p_LARGO, Nullable<decimal> p_ALTO, Nullable<decimal> p_CAPACIDAD, Nullable<decimal> p_REFRIGERADO)
        {
            var p_VENTAIDParameter = p_VENTAID.HasValue ?
                new ObjectParameter("P_VENTAID", p_VENTAID) :
                new ObjectParameter("P_VENTAID", typeof(decimal));
    
            var p_FECHAINICIOParameter = p_FECHAINICIO.HasValue ?
                new ObjectParameter("P_FECHAINICIO", p_FECHAINICIO) :
                new ObjectParameter("P_FECHAINICIO", typeof(System.DateTime));
    
            var p_FECHATERMINOParameter = p_FECHATERMINO.HasValue ?
                new ObjectParameter("P_FECHATERMINO", p_FECHATERMINO) :
                new ObjectParameter("P_FECHATERMINO", typeof(System.DateTime));
    
            var p_ANCHOParameter = p_ANCHO.HasValue ?
                new ObjectParameter("P_ANCHO", p_ANCHO) :
                new ObjectParameter("P_ANCHO", typeof(decimal));
    
            var p_LARGOParameter = p_LARGO.HasValue ?
                new ObjectParameter("P_LARGO", p_LARGO) :
                new ObjectParameter("P_LARGO", typeof(decimal));
    
            var p_ALTOParameter = p_ALTO.HasValue ?
                new ObjectParameter("P_ALTO", p_ALTO) :
                new ObjectParameter("P_ALTO", typeof(decimal));
    
            var p_CAPACIDADParameter = p_CAPACIDAD.HasValue ?
                new ObjectParameter("P_CAPACIDAD", p_CAPACIDAD) :
                new ObjectParameter("P_CAPACIDAD", typeof(decimal));
    
            var p_REFRIGERADOParameter = p_REFRIGERADO.HasValue ?
                new ObjectParameter("P_REFRIGERADO", p_REFRIGERADO) :
                new ObjectParameter("P_REFRIGERADO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_SUBASTA", p_VENTAIDParameter, p_FECHAINICIOParameter, p_FECHATERMINOParameter, p_ANCHOParameter, p_LARGOParameter, p_ALTOParameter, p_CAPACIDADParameter, p_REFRIGERADOParameter);
        }
    
        public virtual int INSERT_SUBASTA_MEDIO(Nullable<decimal> p_MEDIOID, Nullable<decimal> p_SUBASTAID)
        {
            var p_MEDIOIDParameter = p_MEDIOID.HasValue ?
                new ObjectParameter("P_MEDIOID", p_MEDIOID) :
                new ObjectParameter("P_MEDIOID", typeof(decimal));
    
            var p_SUBASTAIDParameter = p_SUBASTAID.HasValue ?
                new ObjectParameter("P_SUBASTAID", p_SUBASTAID) :
                new ObjectParameter("P_SUBASTAID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_SUBASTA_MEDIO", p_MEDIOIDParameter, p_SUBASTAIDParameter);
        }
    
        public virtual int INSERT_TRANSPORTE(string p_TIPOTRANSPORTE, Nullable<System.DateTime> p_FECHATRANSPORTE, string p_ORIGEN, string p_DESTINO, string p_ESTADOTRANSPORTE, Nullable<decimal> p_MEDIOID)
        {
            var p_TIPOTRANSPORTEParameter = p_TIPOTRANSPORTE != null ?
                new ObjectParameter("P_TIPOTRANSPORTE", p_TIPOTRANSPORTE) :
                new ObjectParameter("P_TIPOTRANSPORTE", typeof(string));
    
            var p_FECHATRANSPORTEParameter = p_FECHATRANSPORTE.HasValue ?
                new ObjectParameter("P_FECHATRANSPORTE", p_FECHATRANSPORTE) :
                new ObjectParameter("P_FECHATRANSPORTE", typeof(System.DateTime));
    
            var p_ORIGENParameter = p_ORIGEN != null ?
                new ObjectParameter("P_ORIGEN", p_ORIGEN) :
                new ObjectParameter("P_ORIGEN", typeof(string));
    
            var p_DESTINOParameter = p_DESTINO != null ?
                new ObjectParameter("P_DESTINO", p_DESTINO) :
                new ObjectParameter("P_DESTINO", typeof(string));
    
            var p_ESTADOTRANSPORTEParameter = p_ESTADOTRANSPORTE != null ?
                new ObjectParameter("P_ESTADOTRANSPORTE", p_ESTADOTRANSPORTE) :
                new ObjectParameter("P_ESTADOTRANSPORTE", typeof(string));
    
            var p_MEDIOIDParameter = p_MEDIOID.HasValue ?
                new ObjectParameter("P_MEDIOID", p_MEDIOID) :
                new ObjectParameter("P_MEDIOID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_TRANSPORTE", p_TIPOTRANSPORTEParameter, p_FECHATRANSPORTEParameter, p_ORIGENParameter, p_DESTINOParameter, p_ESTADOTRANSPORTEParameter, p_MEDIOIDParameter);
        }
    
        public virtual int INSERT_USUARIO(string p_NOMBRE, string p_APELLIDO, string p_CORREOELECTRONICO, string p_CONTRASENA, Nullable<decimal> p_TIPOUSUARIOID, string p_DIRECCION, string p_TELEFONO)
        {
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("P_NOMBRE", p_NOMBRE) :
                new ObjectParameter("P_NOMBRE", typeof(string));
    
            var p_APELLIDOParameter = p_APELLIDO != null ?
                new ObjectParameter("P_APELLIDO", p_APELLIDO) :
                new ObjectParameter("P_APELLIDO", typeof(string));
    
            var p_CORREOELECTRONICOParameter = p_CORREOELECTRONICO != null ?
                new ObjectParameter("P_CORREOELECTRONICO", p_CORREOELECTRONICO) :
                new ObjectParameter("P_CORREOELECTRONICO", typeof(string));
    
            var p_CONTRASENAParameter = p_CONTRASENA != null ?
                new ObjectParameter("P_CONTRASENA", p_CONTRASENA) :
                new ObjectParameter("P_CONTRASENA", typeof(string));
    
            var p_TIPOUSUARIOIDParameter = p_TIPOUSUARIOID.HasValue ?
                new ObjectParameter("P_TIPOUSUARIOID", p_TIPOUSUARIOID) :
                new ObjectParameter("P_TIPOUSUARIOID", typeof(decimal));
    
            var p_DIRECCIONParameter = p_DIRECCION != null ?
                new ObjectParameter("P_DIRECCION", p_DIRECCION) :
                new ObjectParameter("P_DIRECCION", typeof(string));
    
            var p_TELEFONOParameter = p_TELEFONO != null ?
                new ObjectParameter("P_TELEFONO", p_TELEFONO) :
                new ObjectParameter("P_TELEFONO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_USUARIO", p_NOMBREParameter, p_APELLIDOParameter, p_CORREOELECTRONICOParameter, p_CONTRASENAParameter, p_TIPOUSUARIOIDParameter, p_DIRECCIONParameter, p_TELEFONOParameter);
        }
    
        public virtual int INSERT_VENTA(Nullable<System.DateTime> p_FECHAVENTA, string p_TIPOVENTA, Nullable<decimal> p_TOTALVENTA, Nullable<decimal> p_ESTADOVENTAID, Nullable<decimal> p_TRANSPORTEID, Nullable<decimal> p_PRODUCTORID, Nullable<decimal> p_CLIENTEID)
        {
            var p_FECHAVENTAParameter = p_FECHAVENTA.HasValue ?
                new ObjectParameter("P_FECHAVENTA", p_FECHAVENTA) :
                new ObjectParameter("P_FECHAVENTA", typeof(System.DateTime));
    
            var p_TIPOVENTAParameter = p_TIPOVENTA != null ?
                new ObjectParameter("P_TIPOVENTA", p_TIPOVENTA) :
                new ObjectParameter("P_TIPOVENTA", typeof(string));
    
            var p_TOTALVENTAParameter = p_TOTALVENTA.HasValue ?
                new ObjectParameter("P_TOTALVENTA", p_TOTALVENTA) :
                new ObjectParameter("P_TOTALVENTA", typeof(decimal));
    
            var p_ESTADOVENTAIDParameter = p_ESTADOVENTAID.HasValue ?
                new ObjectParameter("P_ESTADOVENTAID", p_ESTADOVENTAID) :
                new ObjectParameter("P_ESTADOVENTAID", typeof(decimal));
    
            var p_TRANSPORTEIDParameter = p_TRANSPORTEID.HasValue ?
                new ObjectParameter("P_TRANSPORTEID", p_TRANSPORTEID) :
                new ObjectParameter("P_TRANSPORTEID", typeof(decimal));
    
            var p_PRODUCTORIDParameter = p_PRODUCTORID.HasValue ?
                new ObjectParameter("P_PRODUCTORID", p_PRODUCTORID) :
                new ObjectParameter("P_PRODUCTORID", typeof(decimal));
    
            var p_CLIENTEIDParameter = p_CLIENTEID.HasValue ?
                new ObjectParameter("P_CLIENTEID", p_CLIENTEID) :
                new ObjectParameter("P_CLIENTEID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_VENTA", p_FECHAVENTAParameter, p_TIPOVENTAParameter, p_TOTALVENTAParameter, p_ESTADOVENTAIDParameter, p_TRANSPORTEIDParameter, p_PRODUCTORIDParameter, p_CLIENTEIDParameter);
        }
    
        public virtual int INSERT_VENTA_PRODUCTO(Nullable<decimal> p_VENTAID, Nullable<decimal> p_PRODUCTOID, Nullable<decimal> p_CANTIDAD)
        {
            var p_VENTAIDParameter = p_VENTAID.HasValue ?
                new ObjectParameter("P_VENTAID", p_VENTAID) :
                new ObjectParameter("P_VENTAID", typeof(decimal));
    
            var p_PRODUCTOIDParameter = p_PRODUCTOID.HasValue ?
                new ObjectParameter("P_PRODUCTOID", p_PRODUCTOID) :
                new ObjectParameter("P_PRODUCTOID", typeof(decimal));
    
            var p_CANTIDADParameter = p_CANTIDAD.HasValue ?
                new ObjectParameter("P_CANTIDAD", p_CANTIDAD) :
                new ObjectParameter("P_CANTIDAD", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERT_VENTA_PRODUCTO", p_VENTAIDParameter, p_PRODUCTOIDParameter, p_CANTIDADParameter);
        }
    
        public virtual int PUBLISH_CONTRATO(Nullable<decimal> p_CONTRATOID, Nullable<decimal> p_PUBLISHED)
        {
            var p_CONTRATOIDParameter = p_CONTRATOID.HasValue ?
                new ObjectParameter("P_CONTRATOID", p_CONTRATOID) :
                new ObjectParameter("P_CONTRATOID", typeof(decimal));
    
            var p_PUBLISHEDParameter = p_PUBLISHED.HasValue ?
                new ObjectParameter("P_PUBLISHED", p_PUBLISHED) :
                new ObjectParameter("P_PUBLISHED", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PUBLISH_CONTRATO", p_CONTRATOIDParameter, p_PUBLISHEDParameter);
        }
    
        public virtual int SET_SELECTED_POSTULACION(Nullable<decimal> p_POSTULACIONID, Nullable<decimal> p_SELECTED)
        {
            var p_POSTULACIONIDParameter = p_POSTULACIONID.HasValue ?
                new ObjectParameter("P_POSTULACIONID", p_POSTULACIONID) :
                new ObjectParameter("P_POSTULACIONID", typeof(decimal));
    
            var p_SELECTEDParameter = p_SELECTED.HasValue ?
                new ObjectParameter("P_SELECTED", p_SELECTED) :
                new ObjectParameter("P_SELECTED", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SET_SELECTED_POSTULACION", p_POSTULACIONIDParameter, p_SELECTEDParameter);
        }
    
        public virtual int UPDATE_CONTRATO(Nullable<decimal> p_CONTRATOID, Nullable<System.DateTime> p_FECHAINICIO, Nullable<System.DateTime> p_FECHAFINALIZACION, string p_TIPOCONTRATO, Nullable<decimal> p_ESTADOCONTRATOID, string p_DEMANDA, Nullable<decimal> p_CANTIDAD, Nullable<decimal> p_USUARIOID)
        {
            var p_CONTRATOIDParameter = p_CONTRATOID.HasValue ?
                new ObjectParameter("P_CONTRATOID", p_CONTRATOID) :
                new ObjectParameter("P_CONTRATOID", typeof(decimal));
    
            var p_FECHAINICIOParameter = p_FECHAINICIO.HasValue ?
                new ObjectParameter("P_FECHAINICIO", p_FECHAINICIO) :
                new ObjectParameter("P_FECHAINICIO", typeof(System.DateTime));
    
            var p_FECHAFINALIZACIONParameter = p_FECHAFINALIZACION.HasValue ?
                new ObjectParameter("P_FECHAFINALIZACION", p_FECHAFINALIZACION) :
                new ObjectParameter("P_FECHAFINALIZACION", typeof(System.DateTime));
    
            var p_TIPOCONTRATOParameter = p_TIPOCONTRATO != null ?
                new ObjectParameter("P_TIPOCONTRATO", p_TIPOCONTRATO) :
                new ObjectParameter("P_TIPOCONTRATO", typeof(string));
    
            var p_ESTADOCONTRATOIDParameter = p_ESTADOCONTRATOID.HasValue ?
                new ObjectParameter("P_ESTADOCONTRATOID", p_ESTADOCONTRATOID) :
                new ObjectParameter("P_ESTADOCONTRATOID", typeof(decimal));
    
            var p_DEMANDAParameter = p_DEMANDA != null ?
                new ObjectParameter("P_DEMANDA", p_DEMANDA) :
                new ObjectParameter("P_DEMANDA", typeof(string));
    
            var p_CANTIDADParameter = p_CANTIDAD.HasValue ?
                new ObjectParameter("P_CANTIDAD", p_CANTIDAD) :
                new ObjectParameter("P_CANTIDAD", typeof(decimal));
    
            var p_USUARIOIDParameter = p_USUARIOID.HasValue ?
                new ObjectParameter("P_USUARIOID", p_USUARIOID) :
                new ObjectParameter("P_USUARIOID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_CONTRATO", p_CONTRATOIDParameter, p_FECHAINICIOParameter, p_FECHAFINALIZACIONParameter, p_TIPOCONTRATOParameter, p_ESTADOCONTRATOIDParameter, p_DEMANDAParameter, p_CANTIDADParameter, p_USUARIOIDParameter);
        }
    
        public virtual int UPDATE_MEDIOTRANSPORTE(Nullable<decimal> p_MEDIOID, string p_PATENTE, Nullable<decimal> p_ANCHO, Nullable<decimal> p_LARGO, Nullable<decimal> p_ALTO, Nullable<decimal> p_CAPACIDAD, Nullable<decimal> p_REFRIGERADO, Nullable<decimal> p_PRECIO, Nullable<decimal> p_TRANSPORTISTAID)
        {
            var p_MEDIOIDParameter = p_MEDIOID.HasValue ?
                new ObjectParameter("P_MEDIOID", p_MEDIOID) :
                new ObjectParameter("P_MEDIOID", typeof(decimal));
    
            var p_PATENTEParameter = p_PATENTE != null ?
                new ObjectParameter("P_PATENTE", p_PATENTE) :
                new ObjectParameter("P_PATENTE", typeof(string));
    
            var p_ANCHOParameter = p_ANCHO.HasValue ?
                new ObjectParameter("P_ANCHO", p_ANCHO) :
                new ObjectParameter("P_ANCHO", typeof(decimal));
    
            var p_LARGOParameter = p_LARGO.HasValue ?
                new ObjectParameter("P_LARGO", p_LARGO) :
                new ObjectParameter("P_LARGO", typeof(decimal));
    
            var p_ALTOParameter = p_ALTO.HasValue ?
                new ObjectParameter("P_ALTO", p_ALTO) :
                new ObjectParameter("P_ALTO", typeof(decimal));
    
            var p_CAPACIDADParameter = p_CAPACIDAD.HasValue ?
                new ObjectParameter("P_CAPACIDAD", p_CAPACIDAD) :
                new ObjectParameter("P_CAPACIDAD", typeof(decimal));
    
            var p_REFRIGERADOParameter = p_REFRIGERADO.HasValue ?
                new ObjectParameter("P_REFRIGERADO", p_REFRIGERADO) :
                new ObjectParameter("P_REFRIGERADO", typeof(decimal));
    
            var p_PRECIOParameter = p_PRECIO.HasValue ?
                new ObjectParameter("P_PRECIO", p_PRECIO) :
                new ObjectParameter("P_PRECIO", typeof(decimal));
    
            var p_TRANSPORTISTAIDParameter = p_TRANSPORTISTAID.HasValue ?
                new ObjectParameter("P_TRANSPORTISTAID", p_TRANSPORTISTAID) :
                new ObjectParameter("P_TRANSPORTISTAID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_MEDIOTRANSPORTE", p_MEDIOIDParameter, p_PATENTEParameter, p_ANCHOParameter, p_LARGOParameter, p_ALTOParameter, p_CAPACIDADParameter, p_REFRIGERADOParameter, p_PRECIOParameter, p_TRANSPORTISTAIDParameter);
        }
    
        public virtual int UPDATE_PAGO(Nullable<decimal> p_PAGOID, Nullable<System.DateTime> p_FECHA_PAGO, Nullable<decimal> p_PAGO, Nullable<decimal> p_VENTAID, Nullable<decimal> p_USUARIOID)
        {
            var p_PAGOIDParameter = p_PAGOID.HasValue ?
                new ObjectParameter("P_PAGOID", p_PAGOID) :
                new ObjectParameter("P_PAGOID", typeof(decimal));
    
            var p_FECHA_PAGOParameter = p_FECHA_PAGO.HasValue ?
                new ObjectParameter("P_FECHA_PAGO", p_FECHA_PAGO) :
                new ObjectParameter("P_FECHA_PAGO", typeof(System.DateTime));
    
            var p_PAGOParameter = p_PAGO.HasValue ?
                new ObjectParameter("P_PAGO", p_PAGO) :
                new ObjectParameter("P_PAGO", typeof(decimal));
    
            var p_VENTAIDParameter = p_VENTAID.HasValue ?
                new ObjectParameter("P_VENTAID", p_VENTAID) :
                new ObjectParameter("P_VENTAID", typeof(decimal));
    
            var p_USUARIOIDParameter = p_USUARIOID.HasValue ?
                new ObjectParameter("P_USUARIOID", p_USUARIOID) :
                new ObjectParameter("P_USUARIOID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_PAGO", p_PAGOIDParameter, p_FECHA_PAGOParameter, p_PAGOParameter, p_VENTAIDParameter, p_USUARIOIDParameter);
        }
    
        public virtual int UPDATE_POSTULACION(Nullable<decimal> p_POSTULACIONID, Nullable<decimal> p_PRECIO, Nullable<decimal> p_CANTIDAD, Nullable<System.DateTime> p_FECHACOSECHA, Nullable<decimal> p_CONTRATOID, Nullable<decimal> p_PRODUCTORID)
        {
            var p_POSTULACIONIDParameter = p_POSTULACIONID.HasValue ?
                new ObjectParameter("P_POSTULACIONID", p_POSTULACIONID) :
                new ObjectParameter("P_POSTULACIONID", typeof(decimal));
    
            var p_PRECIOParameter = p_PRECIO.HasValue ?
                new ObjectParameter("P_PRECIO", p_PRECIO) :
                new ObjectParameter("P_PRECIO", typeof(decimal));
    
            var p_CANTIDADParameter = p_CANTIDAD.HasValue ?
                new ObjectParameter("P_CANTIDAD", p_CANTIDAD) :
                new ObjectParameter("P_CANTIDAD", typeof(decimal));
    
            var p_FECHACOSECHAParameter = p_FECHACOSECHA.HasValue ?
                new ObjectParameter("P_FECHACOSECHA", p_FECHACOSECHA) :
                new ObjectParameter("P_FECHACOSECHA", typeof(System.DateTime));
    
            var p_CONTRATOIDParameter = p_CONTRATOID.HasValue ?
                new ObjectParameter("P_CONTRATOID", p_CONTRATOID) :
                new ObjectParameter("P_CONTRATOID", typeof(decimal));
    
            var p_PRODUCTORIDParameter = p_PRODUCTORID.HasValue ?
                new ObjectParameter("P_PRODUCTORID", p_PRODUCTORID) :
                new ObjectParameter("P_PRODUCTORID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_POSTULACION", p_POSTULACIONIDParameter, p_PRECIOParameter, p_CANTIDADParameter, p_FECHACOSECHAParameter, p_CONTRATOIDParameter, p_PRODUCTORIDParameter);
        }
    
        public virtual int UPDATE_PRODUCTOS(Nullable<decimal> p_PRODUCTOID, string p_NOMBRE, Nullable<decimal> p_PRECIO, Nullable<decimal> p_STOCK)
        {
            var p_PRODUCTOIDParameter = p_PRODUCTOID.HasValue ?
                new ObjectParameter("P_PRODUCTOID", p_PRODUCTOID) :
                new ObjectParameter("P_PRODUCTOID", typeof(decimal));
    
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("P_NOMBRE", p_NOMBRE) :
                new ObjectParameter("P_NOMBRE", typeof(string));
    
            var p_PRECIOParameter = p_PRECIO.HasValue ?
                new ObjectParameter("P_PRECIO", p_PRECIO) :
                new ObjectParameter("P_PRECIO", typeof(decimal));
    
            var p_STOCKParameter = p_STOCK.HasValue ?
                new ObjectParameter("P_STOCK", p_STOCK) :
                new ObjectParameter("P_STOCK", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_PRODUCTOS", p_PRODUCTOIDParameter, p_NOMBREParameter, p_PRECIOParameter, p_STOCKParameter);
        }
    
        public virtual int UPDATE_SUBASTA(Nullable<decimal> p_SUBASTAID, Nullable<decimal> p_VENTAID, Nullable<System.DateTime> p_FECHAINICIO, Nullable<System.DateTime> p_FECHATERMINO, Nullable<decimal> p_ANCHO, Nullable<decimal> p_LARGO, Nullable<decimal> p_ALTO, Nullable<decimal> p_CAPACIDAD, Nullable<decimal> p_REFRIGERADO)
        {
            var p_SUBASTAIDParameter = p_SUBASTAID.HasValue ?
                new ObjectParameter("P_SUBASTAID", p_SUBASTAID) :
                new ObjectParameter("P_SUBASTAID", typeof(decimal));
    
            var p_VENTAIDParameter = p_VENTAID.HasValue ?
                new ObjectParameter("P_VENTAID", p_VENTAID) :
                new ObjectParameter("P_VENTAID", typeof(decimal));
    
            var p_FECHAINICIOParameter = p_FECHAINICIO.HasValue ?
                new ObjectParameter("P_FECHAINICIO", p_FECHAINICIO) :
                new ObjectParameter("P_FECHAINICIO", typeof(System.DateTime));
    
            var p_FECHATERMINOParameter = p_FECHATERMINO.HasValue ?
                new ObjectParameter("P_FECHATERMINO", p_FECHATERMINO) :
                new ObjectParameter("P_FECHATERMINO", typeof(System.DateTime));
    
            var p_ANCHOParameter = p_ANCHO.HasValue ?
                new ObjectParameter("P_ANCHO", p_ANCHO) :
                new ObjectParameter("P_ANCHO", typeof(decimal));
    
            var p_LARGOParameter = p_LARGO.HasValue ?
                new ObjectParameter("P_LARGO", p_LARGO) :
                new ObjectParameter("P_LARGO", typeof(decimal));
    
            var p_ALTOParameter = p_ALTO.HasValue ?
                new ObjectParameter("P_ALTO", p_ALTO) :
                new ObjectParameter("P_ALTO", typeof(decimal));
    
            var p_CAPACIDADParameter = p_CAPACIDAD.HasValue ?
                new ObjectParameter("P_CAPACIDAD", p_CAPACIDAD) :
                new ObjectParameter("P_CAPACIDAD", typeof(decimal));
    
            var p_REFRIGERADOParameter = p_REFRIGERADO.HasValue ?
                new ObjectParameter("P_REFRIGERADO", p_REFRIGERADO) :
                new ObjectParameter("P_REFRIGERADO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_SUBASTA", p_SUBASTAIDParameter, p_VENTAIDParameter, p_FECHAINICIOParameter, p_FECHATERMINOParameter, p_ANCHOParameter, p_LARGOParameter, p_ALTOParameter, p_CAPACIDADParameter, p_REFRIGERADOParameter);
        }
    
        public virtual int UPDATE_SUBASTA_MEDIO(Nullable<decimal> p_MEDIOID, Nullable<decimal> p_SUBASTAID, Nullable<decimal> p_SELECTED)
        {
            var p_MEDIOIDParameter = p_MEDIOID.HasValue ?
                new ObjectParameter("P_MEDIOID", p_MEDIOID) :
                new ObjectParameter("P_MEDIOID", typeof(decimal));
    
            var p_SUBASTAIDParameter = p_SUBASTAID.HasValue ?
                new ObjectParameter("P_SUBASTAID", p_SUBASTAID) :
                new ObjectParameter("P_SUBASTAID", typeof(decimal));
    
            var p_SELECTEDParameter = p_SELECTED.HasValue ?
                new ObjectParameter("P_SELECTED", p_SELECTED) :
                new ObjectParameter("P_SELECTED", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_SUBASTA_MEDIO", p_MEDIOIDParameter, p_SUBASTAIDParameter, p_SELECTEDParameter);
        }
    
        public virtual int UPDATE_TRANSPORTE(Nullable<decimal> p_TRANSPORTEID, string p_TIPOTRANSPORTE, Nullable<System.DateTime> p_FECHATRANSPORTE, string p_ORIGEN, string p_DESTINO, string p_ESTADOTRANSPORTE, Nullable<decimal> p_MEDIOID)
        {
            var p_TRANSPORTEIDParameter = p_TRANSPORTEID.HasValue ?
                new ObjectParameter("P_TRANSPORTEID", p_TRANSPORTEID) :
                new ObjectParameter("P_TRANSPORTEID", typeof(decimal));
    
            var p_TIPOTRANSPORTEParameter = p_TIPOTRANSPORTE != null ?
                new ObjectParameter("P_TIPOTRANSPORTE", p_TIPOTRANSPORTE) :
                new ObjectParameter("P_TIPOTRANSPORTE", typeof(string));
    
            var p_FECHATRANSPORTEParameter = p_FECHATRANSPORTE.HasValue ?
                new ObjectParameter("P_FECHATRANSPORTE", p_FECHATRANSPORTE) :
                new ObjectParameter("P_FECHATRANSPORTE", typeof(System.DateTime));
    
            var p_ORIGENParameter = p_ORIGEN != null ?
                new ObjectParameter("P_ORIGEN", p_ORIGEN) :
                new ObjectParameter("P_ORIGEN", typeof(string));
    
            var p_DESTINOParameter = p_DESTINO != null ?
                new ObjectParameter("P_DESTINO", p_DESTINO) :
                new ObjectParameter("P_DESTINO", typeof(string));
    
            var p_ESTADOTRANSPORTEParameter = p_ESTADOTRANSPORTE != null ?
                new ObjectParameter("P_ESTADOTRANSPORTE", p_ESTADOTRANSPORTE) :
                new ObjectParameter("P_ESTADOTRANSPORTE", typeof(string));
    
            var p_MEDIOIDParameter = p_MEDIOID.HasValue ?
                new ObjectParameter("P_MEDIOID", p_MEDIOID) :
                new ObjectParameter("P_MEDIOID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_TRANSPORTE", p_TRANSPORTEIDParameter, p_TIPOTRANSPORTEParameter, p_FECHATRANSPORTEParameter, p_ORIGENParameter, p_DESTINOParameter, p_ESTADOTRANSPORTEParameter, p_MEDIOIDParameter);
        }
    
        public virtual int UPDATE_USUARIOS(Nullable<decimal> p_USUARIOID, string p_NOMBRE, string p_APELLIDO, string p_CORREOELECTRONICO, string p_CONTRASENA, Nullable<decimal> p_TIPOUSUARIOID, string p_DIRECCION, string p_TELEFONO)
        {
            var p_USUARIOIDParameter = p_USUARIOID.HasValue ?
                new ObjectParameter("P_USUARIOID", p_USUARIOID) :
                new ObjectParameter("P_USUARIOID", typeof(decimal));
    
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("P_NOMBRE", p_NOMBRE) :
                new ObjectParameter("P_NOMBRE", typeof(string));
    
            var p_APELLIDOParameter = p_APELLIDO != null ?
                new ObjectParameter("P_APELLIDO", p_APELLIDO) :
                new ObjectParameter("P_APELLIDO", typeof(string));
    
            var p_CORREOELECTRONICOParameter = p_CORREOELECTRONICO != null ?
                new ObjectParameter("P_CORREOELECTRONICO", p_CORREOELECTRONICO) :
                new ObjectParameter("P_CORREOELECTRONICO", typeof(string));
    
            var p_CONTRASENAParameter = p_CONTRASENA != null ?
                new ObjectParameter("P_CONTRASENA", p_CONTRASENA) :
                new ObjectParameter("P_CONTRASENA", typeof(string));
    
            var p_TIPOUSUARIOIDParameter = p_TIPOUSUARIOID.HasValue ?
                new ObjectParameter("P_TIPOUSUARIOID", p_TIPOUSUARIOID) :
                new ObjectParameter("P_TIPOUSUARIOID", typeof(decimal));
    
            var p_DIRECCIONParameter = p_DIRECCION != null ?
                new ObjectParameter("P_DIRECCION", p_DIRECCION) :
                new ObjectParameter("P_DIRECCION", typeof(string));
    
            var p_TELEFONOParameter = p_TELEFONO != null ?
                new ObjectParameter("P_TELEFONO", p_TELEFONO) :
                new ObjectParameter("P_TELEFONO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_USUARIOS", p_USUARIOIDParameter, p_NOMBREParameter, p_APELLIDOParameter, p_CORREOELECTRONICOParameter, p_CONTRASENAParameter, p_TIPOUSUARIOIDParameter, p_DIRECCIONParameter, p_TELEFONOParameter);
        }
    
        public virtual int UPDATE_VENTAS(Nullable<decimal> p_VENTAID, string p_TIPOVENTA, Nullable<System.DateTime> p_FECHAVENTA, Nullable<decimal> p_TOTALVENTA, Nullable<decimal> p_ESTADOVENTAID, Nullable<decimal> p_TRANSPORTEID, Nullable<decimal> p_PRODUCTORID, Nullable<decimal> p_CLIENTEID)
        {
            var p_VENTAIDParameter = p_VENTAID.HasValue ?
                new ObjectParameter("P_VENTAID", p_VENTAID) :
                new ObjectParameter("P_VENTAID", typeof(decimal));
    
            var p_TIPOVENTAParameter = p_TIPOVENTA != null ?
                new ObjectParameter("P_TIPOVENTA", p_TIPOVENTA) :
                new ObjectParameter("P_TIPOVENTA", typeof(string));
    
            var p_FECHAVENTAParameter = p_FECHAVENTA.HasValue ?
                new ObjectParameter("P_FECHAVENTA", p_FECHAVENTA) :
                new ObjectParameter("P_FECHAVENTA", typeof(System.DateTime));
    
            var p_TOTALVENTAParameter = p_TOTALVENTA.HasValue ?
                new ObjectParameter("P_TOTALVENTA", p_TOTALVENTA) :
                new ObjectParameter("P_TOTALVENTA", typeof(decimal));
    
            var p_ESTADOVENTAIDParameter = p_ESTADOVENTAID.HasValue ?
                new ObjectParameter("P_ESTADOVENTAID", p_ESTADOVENTAID) :
                new ObjectParameter("P_ESTADOVENTAID", typeof(decimal));
    
            var p_TRANSPORTEIDParameter = p_TRANSPORTEID.HasValue ?
                new ObjectParameter("P_TRANSPORTEID", p_TRANSPORTEID) :
                new ObjectParameter("P_TRANSPORTEID", typeof(decimal));
    
            var p_PRODUCTORIDParameter = p_PRODUCTORID.HasValue ?
                new ObjectParameter("P_PRODUCTORID", p_PRODUCTORID) :
                new ObjectParameter("P_PRODUCTORID", typeof(decimal));
    
            var p_CLIENTEIDParameter = p_CLIENTEID.HasValue ?
                new ObjectParameter("P_CLIENTEID", p_CLIENTEID) :
                new ObjectParameter("P_CLIENTEID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_VENTAS", p_VENTAIDParameter, p_TIPOVENTAParameter, p_FECHAVENTAParameter, p_TOTALVENTAParameter, p_ESTADOVENTAIDParameter, p_TRANSPORTEIDParameter, p_PRODUCTORIDParameter, p_CLIENTEIDParameter);
        }
    }
}
