//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeriaVirtual.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSTULACION
    {
        public decimal POSTULACIONID { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
        public Nullable<System.DateTime> FECHACOSECHA { get; set; }
        public decimal CONTRATOID { get; set; }
        public decimal PRODUCTORID { get; set; }
        public Nullable<short> SELECTED { get; set; }
    
        public virtual CONTRATOS CONTRATOS { get; set; }
        public virtual PRODUCTOR PRODUCTOR { get; set; }
    }
}
