//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeriaVirtual.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBASTA_MEDIO
    {
        public decimal MEDIOID { get; set; }
        public decimal SUBASTAID { get; set; }
        public Nullable<short> SELECTED { get; set; }
    
        public virtual MEDIOTRANSPORTE MEDIOTRANSPORTE { get; set; }
        public virtual SUBASTA SUBASTA { get; set; }
    }
}
