//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeriaVirtual.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBASTA
    {
        public SUBASTA()
        {
            this.SUBASTA_MEDIO = new HashSet<SUBASTA_MEDIO>();
        }
    
        public decimal SUBASTAID { get; set; }
        public decimal VENTAID { get; set; }
        public Nullable<System.DateTime> FECHAINICIO { get; set; }
        public Nullable<System.DateTime> FECHATERMINO { get; set; }
        public Nullable<decimal> ANCHO_MIN { get; set; }
        public Nullable<decimal> LARGO_MIN { get; set; }
        public Nullable<decimal> ALTO_MIN { get; set; }
        public Nullable<decimal> CAPACIDAD { get; set; }
        public Nullable<short> REFRIGERADO { get; set; }
        public Nullable<short> FINISHED { get; set; }
    
        public virtual ICollection<SUBASTA_MEDIO> SUBASTA_MEDIO { get; set; }
        public virtual VENTAS VENTAS { get; set; }
    }
}
