//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeriaVirtual.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOSUSUARIO
    {
        public TIPOSUSUARIO()
        {
            this.USUARIOS = new HashSet<USUARIOS>();
        }
    
        public decimal TIPOUSUARIOID { get; set; }
        public string NOMBRETIPO { get; set; }
    
        public virtual ICollection<USUARIOS> USUARIOS { get; set; }
    }
}
