//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeriaVirtual.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSPORTE
    {
        public TRANSPORTE()
        {
            this.VENTAS = new HashSet<VENTAS>();
        }
    
        public decimal TRANSPORTEID { get; set; }
        public string TIPOTRANSPORTE { get; set; }
        public Nullable<System.DateTime> FECHATRANSPORTE { get; set; }
        public string ORIGEN { get; set; }
        public string DESTINO { get; set; }
        public string ESTADOTRANSPORTE { get; set; }
        public decimal MEDIOID { get; set; }
    
        public virtual MEDIOTRANSPORTE MEDIOTRANSPORTE { get; set; }
        public virtual ICollection<VENTAS> VENTAS { get; set; }
    }
}
