//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeriaVirtual.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public USUARIOS()
        {
            this.CONTRATOS = new HashSet<CONTRATOS>();
            this.PAGO = new HashSet<PAGO>();
        }
    
        public decimal USUARIOID { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string CORREOELECTRONICO { get; set; }
        public string CONTRASENA { get; set; }
        public decimal TIPOUSUARIOID { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ICollection<CONTRATOS> CONTRATOS { get; set; }
        public virtual ICollection<PAGO> PAGO { get; set; }
        public virtual PRODUCTOR PRODUCTOR { get; set; }
        public virtual TIPOSUSUARIO TIPOSUSUARIO { get; set; }
        public virtual TRANSPORTISTA TRANSPORTISTA { get; set; }
    }
}
